### ISSUE TITLE
Abruf eines Partners: EP2-ID der direkt übergeordneten Organisation ermitteln

### ISSUE THREAD

**Issue by ic-hv** [europace/partner-api#1]
Wäre es möglich in den zurückgegebenen Daten die EP2-ID der direkt übergeordneten Organisation mit zurückzugeben?
Hintergrund: Auf Kundenseite möchte man für Partner, die zur selben Organsiation gehören gleichartige Aktionen durchführen, allerdings geht diese eben nur, wenn es einfachen Weg gibt herauszufinden, welche Organisation in der Hierarchie über dem jeweiligen Partner steht.

**Comment by caspii** [comment]
Siehe https://github.com/hypoport/europace2-api/issues/6

**Comment by ic-hv** [comment]
Wie ist es denn mit dem Fortschritt dieses Tickets bestellt? Wäre schön, wenn sich diese Trivialität baldmöglichst implementiert finden würde ...

**Comment by caspii** [comment]
Hi, ich nehme das ende der Woche in unser Planning mit und gebe dann Bescheid. Für welchen Partner arbeitest Du?

**Comment by caspii** [comment]
hi @ic-hv wie kann ich mit dir Kontakt aufnehmen?

**Comment by ic-hv** [comment]
Hallo Casper, sorry war die letzten Tage im Urlaub. Der Partner für den ich arbeite ist ACCEDO. Meine Email-Adresse müsstest du bereits in deinem Adressbuch haben: vogel(AET)intercorp.de

**Comment by ic-hv** [comment]
Cool, funktioniert im aktuellen Release. Top!
