### ISSUE TITLE
OAuth2 - Flow?

### ISSUE THREAD

**Issue by ic-hv** [europace/partner-api#33]
Ab wann wird diese API auch auf den Client-Credentials OAuth2 - Flow umgestellt werden?

**Comment by gruenewa** [comment]
Hallo @ic-hv, wir haben soeben die PEX v2.0 released. In [diesem Release](https://github.com/europace/partner-api/releases/tag/v2.0) haben wir auf OAuth 2.0 umgestellt. Bitte beachte die Breaking Changes.
