### ISSUE TITLE
Rechte / Zugriffsanpassung via API

### ISSUE THREAD

**Issue by ic-hv** [europace/partner-api#35]
Wenn ich via partner-api einen neuen Partner anlege, muss ich im Nachhinein dann trotzdem wieder in die Benutzeroberfläche wechseln, um ihm unter **Rechte / hat Zugriff auf** noch eine Default-Plakette hinzufügen zu können.

Es wäre schön wenn sich dies auch über die "partner-api" regeln liesse, zumal ja diverse anderweitige Rechte-Einstellungen bereits damit durchgeführt werden können.

**Comment by MikeKrueger75** [comment]
mit `POST https://api.europace.de/v2/partner/{{PARTNER_ID}}/uebernahmeRechtFuer/{{ZIEL_PARTNER_ID}}`
läßt es sich inzwischen umsetzen.

* Voraussetzung: `scope=partner:rechte:schreiben`
