### ISSUE TITLE
PATCH-Operation kommt nicht mit 'Content-Type: application/json-patch+json' zurecht

### ISSUE THREAD

**Issue by ic-hv** [europace/partner-api#43]
Wenn ich Partner-Daten mittels PATCH-Operation anpassen möchte und hierfür den Header 'Content-Type: application/json-patch+json' verwende, schlägt die Operation fehl und es wird der HTTP-Status 415 zurückgegeben.

Ich weiß: In der Dokumentation steht  'Content-Type: application/json'. Wäre allerdings schön, wenn das analog wie bei der Vorgaenge-API https://htmlpreview.github.io/?https://raw.githubusercontent.com/europace/baufismart-vorgaenge-api/master/dokumentation/index.html#_updatevorgang geradegezogen werden könnte - dort muss für PATCH-Operationen der Header 'Content-Type: application/json-patch+json' verwendet werden.

![grafik](https://user-images.githubusercontent.com/26538616/91978700-dcf6f880-ed24-11ea-9722-642f04421861.png)

**Comment by ollio** [comment]
Du würdest zum Ändern der Werte JSON-Patch bevorzugen? Aktuell haben wir aus Gründen der Abwärtskompatibilität ein normales PATCH implementiert und uns mit Content-Negotiation vorbehalten doch noch JSON-Patch zu implementieren

**Comment by ic-hv** [comment]
Naja bevorzugen ist relativ: Es würde mir auch schon reichen wenn der Header 'Content-Type: application/json-patch+json'  auch akzeptiert würde ... aber egal mittlerweile hab' ich einen Workaround in unseren Code implementiert, der für PATCH-Requests an die partner-api dann eben 'Content-Type: application/json' verwendet. Aber vielleicht haben ja auch anderweitige Nutzer ein Interesse daran, das der json-patch - Header akzeptiert wird ... trotzdem schließe ich dieses Issue jetzt.
