### ISSUE TITLE
Unsetting von Daten funktioniert nicht

### ISSUE THREAD

**Issue by ic-hv** [europace/partner-api#44]
Wenn ein Partner-Property, bsp.weise "website", europaceseitig bereits einen Wert != '' hat, dieses Feld dann auf '' (Blank) geändert wird und anschliessend per PATCH-Aufruf an Europace geschickt wird. Dann ignoriert der Europace-seitige Service das Feld, d.h. europace-seitig bleibt der Wert unverändert.

**Comment by ic-hv** [comment]
Ist leider immernoch nicht gefixt ...

**Comment by ic-hv** [comment]
Bemerkung: Das betrifft die neue OAuth2-API

**Comment by ic-hv** [comment]
Eigentlich sollte es laut Doku gehen (siehe: https://github.com/europace/partner-api), aber es geht nicht

![grafik](https://user-images.githubusercontent.com/26538616/103911675-98320280-5106-11eb-9321-89fcacafd07d.png)

**Comment by caspii** [comment]
@ic-hv Danke für die Meldung. Wir arbeiten gerade aktiv an einer Lösung.

**Comment by caspii** [comment]
Müsste jetzt funktionieren!

**Comment by ic-hv** [comment]
Top! Läuft!
