### ISSUE TITLE
untergeordnete statt untergeordnete Partner

### ISSUE THREAD

**Issue by ic-hv** [europace/partner-api#49]
Die Dokumentation ist hier leider etwas inkonsistent:

![inconsistence](https://user-images.githubusercontent.com/26538616/104466742-d8d1c600-55b5-11eb-9204-e7e454dc836a.png)

Ich habs natürlich mit "untergeordnetePartner" umgesetzt gehabt, was leider nicht funktioniert - richtig ist also "untergeordnete" ...

**Comment by huehnerlady** [comment]
@ic-hv vielen Dank für dein Feedback. Ich habe dieses eingebaut und hoffe jetzt ist alles ok.
Wenn noch weiteres falsch ist, melde dich sehr gerne wieder bei uns
