### ISSUE TITLE
partnerId statt id beim Anlegen eines Partners

### ISSUE THREAD

**Issue by ic-hv** [europace/partner-api#50]
In der Dokumentation ist zu sehen, das bei Erzeugung eines Partners, die Ep2-ID in einem Feld mit der Bezeichnung "id" zurückgeliefert wird:

![id](https://user-images.githubusercontent.com/26538616/104559370-93100e80-5644-11eb-9dc8-bb6fa679ed1d.png)

Tatsächlich heisst das Feld aber "partnerId"  ...

![partnerID](https://user-images.githubusercontent.com/26538616/104559421-a8853880-5644-11eb-9604-18792b584cee.png)

**Comment by huehnerlady** [comment]
@ic-hv vielen Dank für dein Feedback. Ich habe dieses eingebaut und hoffe jetzt ist alles ok.
Wenn noch weiteres falsch ist, melde dich sehr gerne wieder bei uns
