### ISSUE TITLE
Bad Request ohne Aussage was kaputt ist

### ISSUE THREAD

**Issue by uweelsholz** [europace/partner-api#59]
# Hintergrund: 

- `“anrede”:“”` geht nicht
  - Lösung: `anrede` weggelassen, falls `null` oder auf einen der enum-Werte `HERR` oder `FRAU` setzen
- `bankverbindung` darf nicht ausschließlich leere Felder enthalten (gemeint ist `{"iban":"","bic":"","kontoinhaber":""}`)
  - Lösung: entweder `{}` (also alle Felder weglassen) oder `bankverbindung` ganz weglassen

Die lapidare Meldung der API: "Request Body ist leer oder nicht lesbar."

**Was brauche ich**: 
- **Sprechendere Fehlermeldungen** was denn eigentlich mein Benutzerfehler ist, denn laut Doku werden "leere" Felder (z.B. `"vorname":""`) ja ignoriert ... stimmt aber nicht (immer).
- **Robusterer Umgang der API mit Doku-konformem Input** (oder Anpassung der Doku bzgl. aktuellem internen Verhalten)

PS: Das kostet enorm viel Zeit, wenn man erst Encoding o.ä. im Verdacht hat und durch Ausprobieren drauf kommen muss

**Comment by MikeKrueger75** [comment]
Hallo Uwe, 

danke für dein Feedback und sorry für die Umstände. 
Ich werde die YAML und die Doku anpassen.

**Comment by MikeKrueger75** [comment]
@huehnerlady testet die Fehlermeldungen im Aufrufpfad nochmal, um ggf. die Fehlermeldung rauszugeben

**Comment by MikeKrueger75** [comment]
@uweelsholz 
Wir haben die YAML angepasst und die Doku um einen Hinweis für die ENUMs erweitert.
