### ISSUE TITLE
ein Partnerkennzeichen wird im embedded-object mit ausgegeben

### ISSUE THREAD

**Issue by MikeKrueger75** [europace/partner-api#7]
Das Partnerkennzeichen "dslSapGeschaeftspartnerNummerFuerRatenkredit" wird im embedded-object (Link-Liste) mit ausgegeben. Das macht keinen Sinn, oder?

**Comment by caspii** [comment]
@MikeKrueger75 kannst du noch ein Beispiel anhängen? Mir ist nicht klar, was Du mit embedded-object meinst

**Comment by MikeKrueger75** [comment]
https://europace.atlassian.net/browse/PARTNER-522

**Comment by MikeKrueger75** [comment]
ist beabsichtigt
