### ISSUE TITLE
FinnSpace-Lasche erfordert separaten Login bei Nutzung von SSI

### ISSUE THREAD

**Issue by ic-hv** [europace/partner-api#70]
Hallo allerseits,

wenn der Kunde sich mittels SSI bei Europace einloggt und auf die FinnSpace-Lasche klickt, wird er zu einem erneuten Login aufgefordert. Lässt sich der SSI derart konfigurieren, das ein zusätzlicher Login zur Nutzung von FinnSpace nicht notwendig ist?

![finn_ssi](https://user-images.githubusercontent.com/26538616/125944401-b2f021dc-db7e-4467-a722-82fa603d681e.png)

Vielen Dank und herzliche Grüße,
Heiko Vogel

**Comment by MikeKrueger75** [comment]
Hallo Heiko,

an dieser Stelle kreuzen sich sich OAuth und SSI ungünstig. Ist kein Benutzername vorhanden, wird der Finnspace gar nicht angezeigt, weil er zwingend eine Benutzer-Authentifizierung benötigt. Verwendet der Benutzer SSI und hat er einen Benutzernamen, kommt es zu diesem Zustand.
Aktuell können wir das Überspringen des Logins nicht umsetzen.

**Comment by MikeKrueger75** [comment]
Wurde gelöst durch neuen SSI-Endpunkt
https://docs.api.europace.de/common/authentifizierung/silent-sign-in-api/
