### ISSUE TITLE
Partner-API akzeptiert seit gestern 13 Uhr keine PATCH-Requests mehr

### ISSUE THREAD

**Issue by ic-hv** [europace/partner-api#82]
Wenn ich einen PATCH Request an https://api.europace.de/v2/partner/ZYT34 mit folgenden Body sende, erhalte ich als Rückgabe einen 400er HTTP-Status und als Antwort {"traceId":"zuul-api-gateway5h6sD","message":"Request Body ist leer oder nicht lesbar."}          

Der Request sieht so aus:

Header:
             Accept: application/json
             Content-Type: application/json
             Content-Length: 523
             
Body:

                    Array
                        (
                            [anrede] => 
                            [email] => thomas.otto@vertrieb.bkm.de
                            [nachname] => Otto
                            [vorname] => Thomas
                            [anschrift] => Array
                                (
                                    [strasse] => Ahornweg
                                    [hausnummer] => 17
                                    [plz] => 99867
                                    [ort] => Gotha
                                )
                            [geburtsdatum] => 1977-08-31
                            [firmenname] => Bausparkasse Mainz AG
                            [faxnummer] => 
                            [mobilnummer] => 
                            [telefonnummer] => 036213840444
                            [webseite] => 
                            [gesperrt] => 
                            [aufsichtsbehoerde] => Industrie- und Handelskammer Erfurt, Arnstädter Str. 34, 99096 Erfurt
                            [registrierungsnummer] => D-W-145-XLZU-34
                            [externePartnerId] => 404001
                            [parent] => Array
                                (
                                    [partnerId] => TFX09
                                )
                        )
               
Wäre net, wenn Ihr prüfen könntet, was das Problem ist.

Danke!

**Comment by ic-hv** [comment]
Nach einem Tipp von Frau Patricia Eifler, habe ich die **fehlende Anrede** ergänzt. Nun wird der Request akzeptiert. 
Es wäre wirklich schön, wenn die API in diesen Fällen eine etwas aussagekräftigere Meldung an den Aufrufer zurückgeben könnte.

Die Meldung "Request Body ist leer oder nicht lesbar." hilft halt leider nicht wirkjlich weiter, zumal im Log des Euroopace Edge-Servers wohl tatsächlich folgendes zu finden sein soll:

> {You only need to give the attributes, who have to change.
> The following rules apply to server-side evaluation:
> empty attributes for strings ("") delete the existing value.
> unknown attributes are ignored.
> partnerId cannot be changed and will be ignored.
> type is not changeable and will be ignored.
> if a field expects an ENUM, a value must be specified (Anrede)} d.h. die Anrede kann nicht gelöscht werden?"

Mit einer Fehlermeldung, die sich an der Log-Meldung oriinetiert, wäöre mir als API-Nutzer schon wesentlich mehr geholfen.

Derweil, herzliche Grüße,
Heiko Vogel

**Comment by MikeKrueger75** [comment]
wird weiterverfolgt in #83
